### ISSUE TITLE
Energy Controls are not functional 

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#18]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/99a06871-8115-4226-b5fc-0fb63cb44c75)

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/af7d2438-c03d-461d-8f0c-c07f9e78e797)

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/b20e5fd1-eef3-42d4-be65-ce5a06bfde41)

### Reproduction steps

1. Calling commands from the GUI

**Comment by Bre77** [comment]
https://github.com/Teslemetry/python-tesla-fleet-api/releases/tag/v0.3.1 Fixes the underlying library issue
The next release will bump and fix this issue.

**Comment by Bre77** [comment]
This should be fixed in https://github.com/Teslemetry/hacs-teslemetry/releases/tag/v1.4.2

**Comment by purcell-lab** [comment]
I couldn't reopen this issue.. However, two energy controls are still not functional:

- Allow Charging from Grid &
- Exports Allowed

[Screen recording 2024-02-10 17.10.54.webm](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/cf506d1a-c389-4abb-9397-8e5019a85308)
[Screen recording 2024-02-10 16.58.37.webm](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/c705f8aa-c799-4194-9c03-f164a936462e)

**Comment by purcell-lab** [comment]
Some logs now to backup analysis:

Set Backup Reserve to 40%
```logs
2024-02-11 19:20:12.053 DEBUG (MainThread) [tesla_fleet_api] Sending request to api/1/energy_sites/XX/backup
2024-02-11 19:20:12.053 DEBUG (MainThread) [tesla_fleet_api] Body: {'backup_reserve_percent': 40}
2024-02-11 19:20:12.566 DEBUG (MainThread) [tesla_fleet_api] Sending request to api/1/energy_sites/XX/live_status
2024-02-11 19:20:13.316 DEBUG (MainThread) [tesla_fleet_api] Response Status: 200
2024-02-11 19:20:13.317 DEBUG (MainThread) [tesla_fleet_api] Response JSON: {'response': {'solar_power': 0, 'energy_left': 23081.210526315786, 'total_pack_energy': 40737, 'percentage_charged': 56.65908271673364, 'backup_capable': True, 'battery_power': 1070, 'load_power': 1070, 'grid_status': 'Active', 'grid_services_active': False, 'grid_power': 0, 'grid_services_power': 0, 'generator_power': 0, 'island_status': 'on_grid', 'storm_mode_active': False, 'timestamp': '2024-02-11T19:20:12+10:00', 'wall_connectors': [{'din': 'XX', 'vin': 'XX', 'wall_connector_state': 5, 'wall_connector_fault_state': 2, 'wall_connector_power': 0}, {'din': 'XX', 'vin': 'XX', 'wall_connector_state': 1, 'wall_connector_fault_state': 8, 'wall_connector_power': 451.1166}]}}
2024-02-11 19:20:13.317 DEBUG (MainThread) [custom_components.teslemetry] Finished fetching Teslemetry Energy Site Live data in 0.751 seconds (success: True)
2024-02-11 19:20:13.912 DEBUG (MainThread) [tesla_fleet_api] Response Status: 200
2024-02-11 19:20:13.913 DEBUG (MainThread) [tesla_fleet_api] Response JSON: {'response': {'code': 201, 'message': 'Updated'}}
2024-02-11 19:20:13.913 DEBUG (MainThread) [custom_components.teslemetry] Command result: {'response': {'code': 201, 'message': 'Updated'}}
2024-02-11 19:20:13.914 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472347049280] 'result'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 111, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/teslemetry/number.py", line 214, in async_set_native_value
    await self.handle_command(self.entity_description.func(self.api, value))
  File "/config/custom_components/teslemetry/entity.py", line 86, in handle_command
    if not result["response"]["result"]:
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'
```

Switch Allow exports:

```logs
2024-02-11 19:20:29.672 DEBUG (MainThread) [tesla_fleet_api] Sending request to api/1/energy_sites/XXX/grid_import_export
2024-02-11 19:20:29.672 DEBUG (MainThread) [tesla_fleet_api] Body: {'disallow_charge_from_grid_with_solar_installed': True}
2024-02-11 19:20:31.333 DEBUG (MainThread) [tesla_fleet_api] Response Status: 200
2024-02-11 19:20:31.334 DEBUG (MainThread) [tesla_fleet_api] Response JSON: {'response': ''}
2024-02-11 19:20:31.334 DEBUG (MainThread) [custom_components.teslemetry] Command result: {'response': ''}
2024-02-11 19:20:31.335 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472347049280] string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/teslemetry/switch.py", line 169, in async_turn_off
    await self.handle_command(self.entity_description.off_func(self.api))
  File "/config/custom_components/teslemetry/entity.py", line 86, in handle_command
    if not result["response"]["result"]:
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by Bre77** [comment]
Right, so energy APIs don't respond the same was as vehicle APIs. Should be an easy fix.

Do you have any idea what an error response looks like? Basically the check I'm doing for vehicles is cases where we return 200 but the command was rejected, for example charging without being plugged in.

**Comment by purcell-lab** [comment]
I don't think we get error responses ;-(  You just notice it hasn't changed on the next status polling, which is very sloppy.

The response is also terrible if it is successful:

```json
{"response":""}
```

The documentation states you should get more ;-(
https://developer.tesla.com/docs/fleet-api#grid_import_export

```json
{
 "response": {
  "code": 204,
  "message": "Updated"
 }
}
```

**Comment by Bre77** [comment]
Can you give https://github.com/Teslemetry/hacs-teslemetry/releases/tag/v1.5.0 a try and let me know if it works any better.

**Comment by purcell-lab** [comment]
Loaded up 1.5.0, the error messages have gone, but the switches are still bouncing around per my videos above.

I'll see if I can get some debug logs later.

**Comment by Bre77** [comment]
Are the problems only related to the [grid_import_export](https://developer.tesla.com/docs/fleet-api#grid_import_export) commands now? I do wonder if I have to send both values even though the documentation says they are optional. The best way to do this is either A) give me permission to randomly issue commands to your powerwall, or B) use something like https://hoppscotch.io/ to send the commands to Teslemetry directly and see what does and doesnt work.

**Comment by purcell-lab** [comment]
No there are a range of issues.

I have a TESLA_API_TOKEN as well, and the curl commands work with just one value.

See video below, controlling via curl I switch to pv_only exports, site info is switched immediately, custom components switches after a few moments and Telemetry select is never switched and is still reading Battery when the mode has switched to pv_only:
[Screen recording 2024-02-12 21.55.48.webm](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/f024ce9e-34f4-4df5-addf-1530b2638fcf)

Next video I try to switch from Battery to SolarOnly exports via Teslemetry, but the command isn't registered and Teslemerty switches itself back to Battery.

[Screen recording 2024-02-12 22.02.01.webm](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/93d3c547-1a68-400e-8ebd-d8c71f31e1c6)

Happy to set you up with a HA login on my machine for testing.

**Comment by purcell-lab** [comment]
1.5.8: Allow Charging from Grid switch fails:

```
2024-02-18 20:25:56.483 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472482639168] 'TeslemetryChargeFromGridSwitchEntity' object has no attribute 'entity_description'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/teslemetry/switch.py", line 246, in async_turn_on
    self.set((self.entity_description.key, True))
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TeslemetryChargeFromGridSwitchEntity' object has no attribute 'entity_description'
```

**Comment by purcell-lab** [comment]
1.5.8: off_grid_reserve

Allows me to change the setting via your slider, even gets a postive response:

```logs
2024-02-18 20:29:43.344 DEBUG (MainThread) [tesla_fleet_api] Sending request to api/1/energy_sites/2252097574301386/off_grid_vehicle_charging_reserve
2024-02-18 20:29:43.345 DEBUG (MainThread) [tesla_fleet_api] Body: {"off_grid_vehicle_charging_reserve_percent": 12}
2024-02-18 20:29:45.186 DEBUG (MainThread) [tesla_fleet_api] Response JSON: {'response': {'off_grid_vehicle_charging_reserve_percent': 12}}
2024-02-18 20:29:45.186 DEBUG (MainThread) [custom_components.teslemetry] Command result: {'response': {'off_grid_vehicle_charging_reserve_percent': 12}}
```

But then during the next status update I get:

```
'off_grid_vehicle_charging_reserve_supported': False
```

**Comment by Bre77** [comment]
`off_grid_reserve` should no longer show up when unsupported, and Storm mode should be fixed.

**Comment by purcell-lab** [comment]
Energy controls working well now.
