### ISSUE TITLE
energy_added state class total increasing

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#61]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I am still seeing the energy_added issue, maybe the threshold check isn't large enough?

This is an ongoing issue with the upstream FleetAPI, with multiple reports for other integrations as well:
https://github.com/home-assistant/core/issues/112558
https://github.com/alandtse/tesla/issues/886

Reported upstream:
https://github.com/teslamotors/vehicle-command/issues/224

### Debug logs

```text
2024-03-30 12:10:10.776 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.m3p_t_charge_energy_added_2 from integration teslemetry has state class total_increasing, but its state is not strictly increasing. Triggered by state 6.413 (6.434) with last_updated set to 2024-03-30T02:07:02.384138+00:00. Please create a bug report at https://github.com/Teslemetry/hacs-teslemetry/issues
```

**Comment by Bre77** [comment]
I believe this issue has been resolved, as the value will only decrease if if drops by over 1kWh. Have you seen this happen recently?

**Comment by purcell-lab** [comment]
I am still getting this error message, from today's logs.

Maybe increase the tolerance to 2 kWh?

```logs
2024-05-13 18:00:10.396 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.m3p_t_charge_energy_added_2 from integration teslemetry has state class total_increasing, but its state is not 
strictly increasing. Triggered by state 5.236 (5.361) with last_updated set to 2024-05-13T07:55:51.930648+00:00. Please create a bug report at https://github.com/Teslemetry/hacs-teslemetry/issues
```

**Comment by tomassanjuann** [comment]
Problem still ocurring on the DC Charged sensor
It happens when HVAC is on when charge is complete and the charger doesn't allow other charging sessions

`Entity sensor.***_dc_charging_energy_in from integration teslemetry has state class total_increasing, but its state is not strictly increasing. Triggered by state 1.02 (1.04) with last_updated set to 2025-07-01T13:01:42.930977+00:00. Please create a bug report at https://github.com/Teslemetry/hass-teslemetry/issues`
