### ISSUE TITLE
Powerwall off_grid_vehicle_charging_reserve_percent not updated in sensor

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#91]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The site_info end point, reports off-grid reserve, in my case currently 20%.
![Screenshot 2024-05-31 11 14 25](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/f750e770-bbe8-4ade-a658-9f75a5f77034)

However this value doesn't seem to come though to the relevant teslemetry sensor:
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/8782dfe0-aea8-49d8-a95b-d708780a0144)

### Reproduction steps

1. Compare site_info endpoint value with sensor

### Debug logs

```text
I note the siteinfo enndpoint off_grid_vehicle_charging_reserve_percent doesn't appear in the diagnostics download. 


{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2024.5.0b1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Australia/Brisbane",
    "os_name": "Linux",
    "os_version": "5.14.0-odroid-arm64",
    "supervisor": "2024.04.4",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "24.0.5",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "huawei_solar": {
      "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
      "version": "1.3.3",
      "requirements": [
        "huawei-solar==2.2.9"
      ]
    },
    "googlewifi": {
      "documentation": "https://github.com/djtimca/hagooglewifi",
      "version": "0.1.34",
      "requirements": [
        "googlewifi==0.0.21"
      ]
    },
    "meross_lan": {
      "documentation": "https://github.com/krahabb/meross_lan",
      "version": "5.0.4",
      "requirements": []
    },
    "tesla_custom": {
      "documentation": "https://github.com/alandtse/tesla/wiki",
      "version": "3.21.0",
      "requirements": [
        "teslajsonpy==3.10.3"
      ]
    },
    "dyson_cloud": {
      "documentation": "https://github.com/shenxn/ha-dyson",
      "version": "0.15.0",
      "requirements": [
        "libdyson==0.8.7"
      ]
    },
    "solaredge_modbus_multi": {
      "documentation": "https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki",
      "version": "2.4.14-pre.3",
      "requirements": [
        "pymodbus>=3.6.6"
      ]
    },
    "garmin_connect": {
      "documentation": "https://github.com/cyberjunky/home-assistant-garmin_connect",
      "version": "0.2.19",
      "requirements": [
        "garminconnect==0.2.12",
        "tzlocal"
      ]
    },
    "solar_optimizer": {
      "documentation": "https://github.com/jmcollin78/solar_optimizer",
      "version": "3.0.0",
      "requirements": []
    },
    "miele": {
      "documentation": "https://github.com/astrandb/miele",
      "version": "2024.3.0",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.7"
      ]
    },
    "scheduler": {
      "documentation": "https://github.com/nielsfaber/scheduler-component",
      "version": "v0.0.0",
      "requirements": []
    },
    "climate_template": {
      "documentation": "https://github.com/jcwillox/hass-template-climate",
      "version": "0.6.1",
      "requirements": []
    },
    "dyson_local": {
      "documentation": "https://github.com/libdyson-wg/ha-dyson",
      "version": "1.3.11",
      "requirements": []
    },
    "versatile_thermostat": {
      "documentation": "https://github.com/jmcollin78/versatile_thermostat",
      "version": "6.2.3",
      "requirements": []
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.2.7",
      "requirements": []
    },
    "smartthinq_sensors": {
      "documentation": "https://github.com/ollo69/ha-smartthinq-sensors",
      "version": "0.39.0",
      "requirements": [
        "pycountry>=23.0.0",
        "xmltodict>=0.13.0",
        "charset_normalizer>=3.2.0"
      ]
    },
    "solcast_solar": {
      "documentation": "https://github.com/oziee/ha-solcast-solar",
      "version": "v4.0.16",
      "requirements": [
        "aiohttp>=3.8.5",
        "datetime>=4.3",
        "isodate>=0.6.1"
      ]
    },
    "tplink_easy_smart": {
      "documentation": "https://github.com/vmakeev/tplink_easy_smart",
      "version": "0.3.0",
      "requirements": [
        "json5==0.9.10"
      ]
    },
    "solarweb": {
      "documentation": "https://github.com/drc38/Fronius_solarweb",
      "version": "0.2.3",
      "requirements": [
        "fronius-solarweb>=0.2.0"
      ]
    },
    "deebot": {
      "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
      "version": "3.0.0",
      "requirements": [
        "deebot-client==4.0.0",
        "numpy>=1.23.2"
      ]
    },
    "nintendo_parental": {
      "documentation": "https://github.com/pantherale0/ha-nintendoparentalcontrols",
      "version": "2024.4.0",
      "requirements": [
        "pynintendoparental==0.5.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "bureau_of_meteorology": {
      "documentation": "https://github.com/bremor/bureau_of_meteorology",
      "version": "1.2.0",
      "requirements": [
        "iso8601"
      ]
    },
    "powercalc": {
      "documentation": "https://github.com/bramstroker/homeassistant-powercalc",
      "version": "v1.12.0-beta.6",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "opennem": {
      "documentation": "https://github.com/bacco007/sensor.opennem",
      "version": "2022.09.1",
      "requirements": []
    },
    "solaredge_modbus": {
      "documentation": "https://github.com/binsentsu/home-assistant-solaredge-modbus",
      "version": "1.11.1",
      "requirements": [
        "pymodbus==3.5.4"
      ]
    },
    "teslemetry": {
      "documentation": "https://www.home-assistant.io/integrations/teslemetry",
      "version": "v1.8.18",
      "requirements": [
        "tesla-fleet-api==0.5.6",
        "teslemetry-stream==0.2.3"
      ]
    },
    "tesla_gateway": {
      "documentation": "https://github.com/carboncoop/tesla-gateway-ha-component",
      "version": "0.1.0",
      "requirements": [
        "teslapy==2.8.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "teslemetry",
    "name": "Teslemetry",
    "codeowners": [
      "@Bre77"
    ],
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/teslemetry",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/Teslemetry/hacs-teslemetry/issues",
    "loggers": [
      "tesla_fleet_api",
      "teslemetry_stream"
    ],
    "requirements": [
      "tesla-fleet-api==0.5.6",
      "teslemetry-stream==0.2.3"
    ],
    "version": "v1.8.18",
    "is_built_in": false
  },
  "data": {
    "vehicles": [
      {
        "data": {
          "id": "**REDACTED**",
          "user_id": "**REDACTED**",
          "vehicle_id": "**REDACTED**",
          "vin": "**REDACTED**",
          "color": null,
          "access_type": "DRIVER",
          "granular_access_hide_private": false,
          "tokens": "**REDACTED**",
          "state": "online",
          "in_service": false,
          "id_s": "**REDACTED**",
          "calendar_enabled": true,
          "api_version": 75,
          "backseat_token": null,
          "backseat_token_updated_at": null,
          "share_type_s": "ADD_DRIVER_EXTERNAL",
          "ble_autopair_enrolled": false,
          "charge_state_battery_heater_on": false,
          "charge_state_battery_level": 36,
          "charge_state_battery_range": 95.25,
          "charge_state_charge_amps": 16,
          "charge_state_charge_current_request": 16,
          "charge_state_charge_current_request_max": 16,
          "charge_state_charge_enable_request": true,
          "charge_state_charge_energy_added": 1.82,
          "charge_state_charge_limit_soc": 100,
          "charge_state_charge_limit_soc_max": 100,
          "charge_state_charge_limit_soc_min": 50,
          "charge_state_charge_limit_soc_std": 80,
          "charge_state_charge_miles_added_ideal": 8.0,
          "charge_state_charge_miles_added_rated": 8.0,
          "charge_state_charge_port_cold_weather_mode": false,
          "charge_state_charge_port_color": "<invalid>",
          "charge_state_charge_port_door_open": false,
          "charge_state_charge_port_latch": "Engaged",
          "charge_state_charge_rate": 0.0,
          "charge_state_charger_actual_current": 0,
          "charge_state_charger_phases": null,
          "charge_state_charger_pilot_current": 16,
          "charge_state_charger_power": 0,
          "charge_state_charger_voltage": 2,
          "charge_state_charging_state": "Disconnected",
          "charge_state_conn_charge_cable": "<invalid>",
          "charge_state_est_battery_range": 109.14,
          "charge_state_fast_charger_brand": "<invalid>",
          "charge_state_fast_charger_present": false,
          "charge_state_fast_charger_type": "<invalid>",
          "charge_state_ideal_battery_range": 95.25,
          "charge_state_max_range_charge_counter": 7,
          "charge_state_minutes_to_full_charge": 0,
          "charge_state_not_enough_power_to_heat": null,
          "charge_state_off_peak_charging_enabled": false,
          "charge_state_off_peak_charging_times": "all_week",
          "charge_state_off_peak_hours_end_time": 360,
          "charge_state_preconditioning_enabled": false,
          "charge_state_preconditioning_times": "all_week",
          "charge_state_scheduled_charging_mode": "Off",
          "charge_state_scheduled_charging_pending": false,
          "charge_state_scheduled_charging_start_time": null,
          "charge_state_scheduled_charging_start_time_app": 0,
          "charge_state_scheduled_departure_time": 1713308400,
          "charge_state_scheduled_departure_time_minutes": 540,
          "charge_state_supercharger_session_trip_planner": false,
          "charge_state_time_to_full_charge": 0.0,
          "charge_state_timestamp": 1714213923474,
          "charge_state_trip_charging": false,
          "charge_state_usable_battery_level": 36,
          "charge_state_user_charge_enable_request": null,
          "climate_state_allow_cabin_overheat_protection": true,
          "climate_state_auto_seat_climate_left": false,
          "climate_state_auto_seat_climate_right": false,
          "climate_state_auto_steering_wheel_heat": false,
          "climate_state_battery_heater": false,
          "climate_state_battery_heater_no_power": null,
          "climate_state_bioweapon_mode": false,
          "climate_state_cabin_overheat_protection": "On",
          "climate_state_cabin_overheat_protection_actively_cooling": false,
          "climate_state_climate_keeper_mode": "camp",
          "climate_state_cop_activation_temperature": "High",
          "climate_state_defrost_mode": 0,
          "climate_state_driver_temp_setting": 21.0,
          "climate_state_fan_status": 2,
          "climate_state_hvac_auto_request": "On",
          "climate_state_inside_temp": 21.0,
          "climate_state_is_auto_conditioning_on": true,
          "climate_state_is_climate_on": true,
          "climate_state_is_front_defroster_on": false,
          "climate_state_is_preconditioning": false,
          "climate_state_is_rear_defroster_on": false,
          "climate_state_left_temp_direction": -95,
          "climate_state_max_avail_temp": 28.0,
          "climate_state_min_avail_temp": 15.0,
          "climate_state_outside_temp": 27.5,
          "climate_state_passenger_temp_setting": 21.0,
          "climate_state_remote_heater_control_enabled": true,
          "climate_state_right_temp_direction": -95,
          "climate_state_seat_heater_left": 0,
          "climate_state_seat_heater_rear_center": 0,
          "climate_state_seat_heater_rear_left": 0,
          "climate_state_seat_heater_rear_right": 0,
          "climate_state_seat_heater_right": 0,
          "climate_state_side_mirror_heaters": false,
          "climate_state_steering_wheel_heat_level": 0,
          "climate_state_steering_wheel_heater": false,
          "climate_state_supports_fan_only_cabin_overheat_protection": true,
          "climate_state_timestamp": 1714213923474,
          "climate_state_wiper_blade_heater": false,
          "drive_state_active_route_energy_at_arrival": 41,
          "drive_state_active_route_latitude": "**REDACTED**",
          "drive_state_active_route_longitude": "**REDACTED**",
          "drive_state_active_route_traffic_minutes_delay": 0.0,
          "drive_state_gps_as_of": 1714213922,
          "drive_state_heading": 178,
          "drive_state_latitude": "**REDACTED**",
          "drive_state_longitude": "**REDACTED**",
          "drive_state_native_latitude": "**REDACTED**",
          "drive_state_native_location_supported": 1,
          "drive_state_native_longitude": "**REDACTED**",
          "drive_state_native_type": "wgs",
          "drive_state_power": 0,
          "drive_state_shift_state": null,
          "drive_state_speed": null,
          "drive_state_timestamp": 1714213923474,
          "vehicle_config_aux_park_lamps": "None",
          "vehicle_config_badge_version": 1,
          "vehicle_config_can_accept_navigation_requests": true,
          "vehicle_config_can_actuate_trunks": true,
          "vehicle_config_car_special_type": "base",
          "vehicle_config_car_type": "modely",
          "vehicle_config_charge_port_type": "CCS",
          "vehicle_config_cop_user_set_temp_supported": false,
          "vehicle_config_dashcam_clip_save_supported": true,
          "vehicle_config_default_charge_to_max": true,
          "vehicle_config_driver_assist": "TeslaAP3",
          "vehicle_config_ece_restrictions": false,
          "vehicle_config_efficiency_package": "MYSRPlus2021Q3GFSH",
          "vehicle_config_eu_vehicle": true,
          "vehicle_config_exterior_color": "SolidBlack",
          "vehicle_config_exterior_trim": "Black",
          "vehicle_config_exterior_trim_override": "",
          "vehicle_config_has_air_suspension": false,
          "vehicle_config_has_ludicrous_mode": false,
          "vehicle_config_has_seat_cooling": false,
          "vehicle_config_headlamp_type": "Global",
          "vehicle_config_interior_trim_type": "White2",
          "vehicle_config_key_version": 2,
          "vehicle_config_motorized_charge_port": true,
          "vehicle_config_paint_color_override": "5,182,255,0.7,0.04",
          "vehicle_config_performance_package": "Base2022",
          "vehicle_config_plg": true,
          "vehicle_config_pws": true,
          "vehicle_config_rear_drive_unit": "PM216MOSFET",
          "vehicle_config_rear_seat_heaters": 1,
          "vehicle_config_rear_seat_type": 0,
          "vehicle_config_rhd": true,
          "vehicle_config_roof_color": "RoofColorGlass",
          "vehicle_config_seat_type": null,
          "vehicle_config_spoiler_type": "None",
          "vehicle_config_sun_roof_installed": null,
          "vehicle_config_supports_qr_pairing": false,
          "vehicle_config_third_row_seats": "None",
          "vehicle_config_timestamp": 1714213923474,
          "vehicle_config_trim_badging": "50",
          "vehicle_config_use_range_badging": true,
          "vehicle_config_utc_offset": 36000,
          "vehicle_config_webcam_selfie_supported": true,
          "vehicle_config_webcam_supported": true,
          "vehicle_config_wheel_type": "Induction20Black",
          "vehicle_state_api_version": 75,
          "vehicle_state_autopark_state_v2": "unavailable",
          "vehicle_state_calendar_supported": true,
          "vehicle_state_car_version": "2024.8.9 0cac3042b6cd",
          "vehicle_state_center_display_state": 2,
          "vehicle_state_dashcam_clip_save_available": true,
          "vehicle_state_dashcam_state": "Recording",
          "vehicle_state_df": 0,
          "vehicle_state_dr": 0,
          "vehicle_state_fd_window": 1,
          "vehicle_state_feature_bitmask": "fbdffbff,4b87f",
          "vehicle_state_fp_window": 0,
          "vehicle_state_ft": 0,
          "vehicle_state_is_user_present": true,
          "vehicle_state_locked": false,
          "vehicle_state_media_info_a2dp_source_name": "Pixel 8 Pro",
          "vehicle_state_media_info_audio_volume": 2.6667,
          "vehicle_state_media_info_audio_volume_increment": 0.333333,
          "vehicle_state_media_info_audio_volume_max": 10.333333,
          "vehicle_state_media_info_media_playback_status": "Stopped",
          "vehicle_state_media_info_now_playing_album": "",
          "vehicle_state_media_info_now_playing_artist": "",
          "vehicle_state_media_info_now_playing_duration": 0,
          "vehicle_state_media_info_now_playing_elapsed": 0,
          "vehicle_state_media_info_now_playing_source": "Spotify",
          "vehicle_state_media_info_now_playing_station": "",
          "vehicle_state_media_info_now_playing_title": "",
          "vehicle_state_media_state_remote_control_enabled": true,
          "vehicle_state_notifications_supported": true,
          "vehicle_state_odometer": 12552.405178,
          "vehicle_state_parsed_calendar_supported": true,
          "vehicle_state_pf": 0,
          "vehicle_state_pr": 0,
          "vehicle_state_rd_window": 0,
          "vehicle_state_remote_start": false,
          "vehicle_state_remote_start_enabled": true,
          "vehicle_state_remote_start_supported": true,
          "vehicle_state_rp_window": 0,
          "vehicle_state_rt": 0,
          "vehicle_state_santa_mode": 0,
          "vehicle_state_sentry_mode": false,
          "vehicle_state_sentry_mode_available": false,
          "vehicle_state_service_mode": false,
          "vehicle_state_service_mode_plus": false,
          "vehicle_state_software_update_download_perc": 0,
          "vehicle_state_software_update_expected_duration_sec": 2700,
          "vehicle_state_software_update_install_perc": 1,
          "vehicle_state_software_update_status": "",
          "vehicle_state_software_update_version": " ",
          "vehicle_state_speed_limit_mode_active": false,
          "vehicle_state_speed_limit_mode_current_limit_mph": 85.0,
          "vehicle_state_speed_limit_mode_max_limit_mph": 120,
          "vehicle_state_speed_limit_mode_min_limit_mph": 50.0,
          "vehicle_state_speed_limit_mode_pin_code_set": false,
          "vehicle_state_timestamp": 1714213923473,
          "vehicle_state_tpms_hard_warning_fl": false,
          "vehicle_state_tpms_hard_warning_fr": false,
          "vehicle_state_tpms_hard_warning_rl": false,
          "vehicle_state_tpms_hard_warning_rr": false,
          "vehicle_state_tpms_last_seen_pressure_time_fl": 1714200130,
          "vehicle_state_tpms_last_seen_pressure_time_fr": 1714200130,
          "vehicle_state_tpms_last_seen_pressure_time_rl": 1714200130,
          "vehicle_state_tpms_last_seen_pressure_time_rr": 1714200130,
          "vehicle_state_tpms_pressure_fl": 2.875,
          "vehicle_state_tpms_pressure_fr": 2.925,
          "vehicle_state_tpms_pressure_rl": 2.9,
          "vehicle_state_tpms_pressure_rr": 2.9,
          "vehicle_state_tpms_rcp_front_value": 2.9,
          "vehicle_state_tpms_rcp_rear_value": 2.9,
          "vehicle_state_tpms_soft_warning_fl": false,
          "vehicle_state_tpms_soft_warning_fr": false,
          "vehicle_state_tpms_soft_warning_rl": false,
          "vehicle_state_tpms_soft_warning_rr": false,
          "vehicle_state_valet_mode": false,
          "vehicle_state_valet_pin_needed": false,
          "vehicle_state_vehicle_name": "Betty",
          "vehicle_state_vehicle_self_test_progress": 0,
          "vehicle_state_vehicle_self_test_requested": false,
          "vehicle_state_webcam_available": true
        },
        "stream": {
          "config": {
            "hostname": null,
            "fields": null,
            "alerts": null
          },
          "connected": false
        }
      },
      {
        "data": {
          "id": "**REDACTED**",
          "user_id": "**REDACTED**",
          "vehicle_id": "**REDACTED**",
          "vin": "**REDACTED**",
          "color": null,
          "access_type": "OWNER",
          "display_name": "Duka",
          "option_codes": "AD15,AF00,APFB,APH4,AU3P,BC3R,BT37,CDM0,CH06,COAU,DRRH,DV4W,FC3P,FG31,FM3P,GLFR,HL31,HM30,ID3W,IL31,LTPB,MDL3,MR30,PMNG,PC31,REAP,RF3G,RS3H,S3PB,SA3P,SC04,STCP,SU3C,T3M3,TM00,TW00,UT3P,W32D,WR00,ZINV,MI01,PL31,SLR1,ST30,BG32,I38M,OSSB,AUF1,RSF1,ILF1,FGF1,CPF1,HP30,PT00",
          "granular_access_hide_private": false,
          "tokens": "**REDACTED**",
          "state": "offline",
          "in_service": false,
          "id_s": "**REDACTED**",
          "calendar_enabled": true,
          "api_version": 75,
          "backseat_token": null,
          "backseat_token_updated_at": null,
          "ble_autopair_enrolled": false,
          "command_signing": "allowed",
          "release_notes_supported": true
        },
        "stream": {
          "config": {
            "hostname": "au-test.teslemetry.com",
            "fields": {
              "ACChargingEnergyIn": {
                "interval_seconds": 60
              },
              "ACChargingPower": {
                "interval_seconds": 15
              },
              "BMSState": {
                "interval_seconds": 200
              },
              "BatteryLevel": {
                "interval_seconds": 80
              },
              "BrickVoltageMax": {
                "interval_seconds": 200
              },
              "ChargeAmps": {
                "interval_seconds": 200
              },
              "ChargeEnableRequest": {
                "interval_seconds": 200
              },
              "ChargePort": {
                "interval_seconds": 200
              },
              "ChargePortLatch": {
                "interval_seconds": 200
              },
              "ChargeState": {
                "interval_seconds": 200
              },
              "DCDCEnable": {
                "interval_seconds": 200
              },
              "DestinationLocation": {
                "interval_seconds": 200
              },
              "DriveRail": {
                "interval_seconds": 200
              },
              "EnergyRemaining": {
                "interval_seconds": 200
              },
              "Location": {
                "interval_seconds": 200
              },
              "PackCurrent": {
                "interval_seconds": 200
              },
              "PackVoltage": {
                "interval_seconds": 200
              }
            },
            "alerts": [
              "customer"
            ]
          },
          "connected": true
        }
      }
    ],
    "energysites": [
      {
        "live": {
          "solar_power": 0,
          "percentage_charged": 15.571841548072445,
          "backup_capable": true,
          "battery_power": 830,
          "load_power": 830,
          "grid_status": "Active",
          "grid_services_active": false,
          "grid_power": 0,
          "grid_services_power": 0,
          "generator_power": 0,
          "island_status": "on_grid",
          "storm_mode_active": false,
          "timestamp": "2024-04-27T20:32:03+10:00",
          "wall_connectors": {
            "1529455-02-E--PGT22325087207": {
              "din": "1529455-02-E--PGT22325087207",
              "wall_connector_state": 2,
              "wall_connector_fault_state": 2,
              "wall_connector_power": 0
            },
            "1529455-02-E--PGT22325086977": {
              "din": "1529455-02-E--PGT22325086977",
              "vin": "**REDACTED**",
              "wall_connector_state": 4,
              "wall_connector_fault_state": 2,
              "wall_connector_power": 0
            }
          }
        },
        "info": {
          "id": "1152100-14-J--CN321293G4J50D",
          "site_name": "Gateway",
          "backup_reserve_percent": 0,
          "default_real_mode": "autonomous",
          "installation_date": "**REDACTED**",
          "user_settings_go_off_grid_test_banner_enabled": false,
          "user_settings_storm_mode_enabled": true,
          "user_settings_powerwall_onboarding_settings_set": true,
          "user_settings_powerwall_tesla_electric_interested_in": false,
          "user_settings_vpp_tour_enabled": true,
          "user_settings_sync_grid_alert_enabled": true,
          "user_settings_breaker_alert_enabled": false,
          "components_solar": true,
          "components_solar_type": "pv_panel",
          "components_battery": true,
          "components_grid": true,
          "components_backup": true,
          "components_gateway": "teg",
          "components_load_meter": true,
          "components_tou_capable": true,
          "components_storm_mode_capable": true,
          "components_flex_energy_request_capable": false,
          "components_car_charging_data_supported": false,
          "components_off_grid_vehicle_charging_reserve_supported": false,
          "components_vehicle_charging_performance_view_enabled": false,
          "components_vehicle_charging_solar_offset_view_enabled": false,
          "components_battery_solar_offset_view_enabled": true,
          "components_solar_value_enabled": true,
          "components_energy_value_header": "Energy Value",
          "components_energy_value_subheader": "Estimated Value",
          "components_energy_service_self_scheduling_enabled": true,
          "components_show_grid_import_battery_source_cards": true,
          "components_set_islanding_mode_enabled": true,
          "components_wifi_commissioning_enabled": true,
          "components_backup_time_remaining_enabled": true,
          "components_battery_type": "ac_powerwall",
          "components_configurable": true,
          "components_grid_services_enabled": false,
          "components_gateways": [
            {
              "device_id": "28d43400-3e08-4f2f-99e0-aaf55bfb09a2",
              "din": "1152100-14-J--CN321293G4J50D",
              "serial_number": "CN321293G4J50D",
              "part_number": "1152100-14-J",
              "part_type": 10,
              "part_name": "Tesla Backup Gateway 2",
              "is_active": true,
              "site_id": "6ceeeb74-7df9-4e37-91d1-18c7fdee2ea3",
              "firmware_version": "24.4.0 0fe780c9",
              "updated_datetime": "2024-04-26T22:14:37.02Z"
            }
          ],
          "components_batteries": [
            {
              "device_id": "388484da-b016-42cf-ad8e-be338f9e7882",
              "din": "3012170-05-C--TG1222020024E9",
              "serial_number": "TG1222020024E9",
              "part_number": "3012170-05-C",
              "part_type": 2,
              "part_name": "Powerwall 2",
              "nameplate_max_charge_power": 5000,
              "nameplate_max_discharge_power": 5000,
              "nameplate_energy": 13500
            },
            {
              "device_id": "a556aade-084f-4012-b1b3-23981a07a8b7",
              "din": "3012170-10-B--TG122010001DA5",
              "serial_number": "TG122010001DA5",
              "part_number": "3012170-10-B",
              "part_type": 2,
              "part_name": "Powerwall 2",
              "nameplate_max_charge_power": 5000,
              "nameplate_max_discharge_power": 5000,
              "nameplate_energy": 13500
            },
            {
              "device_id": "efaa20fd-9b38-41cc-88a4-9e3417ff8c1c",
              "din": "3012170-05-C--TG1222020024C8",
              "serial_number": "TG1222020024C8",
              "part_number": "3012170-05-C",
              "part_type": 2,
              "part_name": "Powerwall 2",
              "nameplate_max_charge_power": 5000,
              "nameplate_max_discharge_power": 5000,
              "nameplate_energy": 13500
            }
          ],
          "components_wall_connectors": [
            {
              "device_id": "a4936580-75de-4833-a032-52f882188749",
              "din": "1529455-02-E--PGT22325087207",
              "part_number": "1529455-02-E",
              "part_type": 15,
              "part_name": "Gen 3 Wall Connector",
              "is_active": true
            },
            {
              "device_id": "216ab0d7-84d6-4aac-baa8-9ada56095440",
              "din": "1529455-02-E--PGT22325086977",
              "part_number": "1529455-02-E",
              "part_type": 15,
              "part_name": "Gen 3 Wall Connector",
              "is_active": true
            }
          ],
          "components_customer_preferred_export_rule": "pv_only",
          "components_net_meter_mode": "battery_ok",
          "components_system_alerts_enabled": true,
          "version": "24.4.0 0fe780c9",
          "battery_count": 3,
          "tariff_content_code": "(edited)",
          "tariff_content_name": "Weekenf (edited)",
          "tariff_content_utility": "Amber",
          "tariff_content_daily_charges": [
            {
              "amount": 0,
              "name": "Charge"
            }
          ],
          "tariff_content_demand_charges_ALL_ALL": 0,
          "tariff_content_energy_charges_ALL_ALL": 0,
          "tariff_content_energy_charges_Summer_OFF_PEAK": 0.15,
          "tariff_content_energy_charges_Summer_ON_PEAK": 0.5,
          "tariff_content_energy_charges_Summer_PARTIAL_PEAK": 0.38,
          "tariff_content_energy_charges_Summer_SUPER_OFF_PEAK": 0.04,
          "tariff_content_seasons_Summer_fromDay": 1,
          "tariff_content_seasons_Summer_toDay": 31,
          "tariff_content_seasons_Summer_fromMonth": 1,
          "tariff_content_seasons_Summer_toMonth": 12,
          "tariff_content_seasons_Summer_tou_periods_OFF_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 0,
              "fromMinute": 0,
              "toHour": 9,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 14,
              "fromMinute": 0,
              "toHour": 16,
              "toMinute": 0
            }
          ],
          "tariff_content_seasons_Summer_tou_periods_ON_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 17,
              "fromMinute": 0,
              "toHour": 19,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 0,
              "toHour": 22,
              "toMinute": 30
            }
          ],
          "tariff_content_seasons_Summer_tou_periods_PARTIAL_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 16,
              "fromMinute": 0,
              "toHour": 17,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 19,
              "fromMinute": 0,
              "toHour": 22,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 30,
              "toHour": 0,
              "toMinute": 0
            }
          ],
          "tariff_content_seasons_Summer_tou_periods_SUPER_OFF_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 9,
              "fromMinute": 0,
              "toHour": 14,
              "toMinute": 0
            }
          ],
          "tariff_content_seasons_Winter_fromDay": 0,
          "tariff_content_seasons_Winter_toDay": 0,
          "tariff_content_seasons_Winter_fromMonth": 0,
          "tariff_content_seasons_Winter_toMonth": 0,
          "tariff_content_sell_tariff_name": "Weekenf (edited)",
          "tariff_content_sell_tariff_utility": "Amber",
          "tariff_content_sell_tariff_daily_charges": [
            {
              "amount": 0,
              "name": "Charge"
            }
          ],
          "tariff_content_sell_tariff_demand_charges_ALL_ALL": 0,
          "tariff_content_sell_tariff_energy_charges_ALL_ALL": 0,
          "tariff_content_sell_tariff_energy_charges_Summer_OFF_PEAK": 0.05,
          "tariff_content_sell_tariff_energy_charges_Summer_ON_PEAK": 0.35,
          "tariff_content_sell_tariff_energy_charges_Summer_PARTIAL_PEAK": 0.1,
          "tariff_content_sell_tariff_energy_charges_Summer_SUPER_OFF_PEAK": 0,
          "tariff_content_sell_tariff_seasons_Summer_fromDay": 1,
          "tariff_content_sell_tariff_seasons_Summer_toDay": 31,
          "tariff_content_sell_tariff_seasons_Summer_fromMonth": 1,
          "tariff_content_sell_tariff_seasons_Summer_toMonth": 12,
          "tariff_content_sell_tariff_seasons_Summer_tou_periods_OFF_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 0,
              "fromMinute": 0,
              "toHour": 9,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 14,
              "fromMinute": 0,
              "toHour": 16,
              "toMinute": 0
            }
          ],
          "tariff_content_sell_tariff_seasons_Summer_tou_periods_ON_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 17,
              "fromMinute": 0,
              "toHour": 19,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 0,
              "toHour": 22,
              "toMinute": 30
            }
          ],
          "tariff_content_sell_tariff_seasons_Summer_tou_periods_PARTIAL_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 16,
              "fromMinute": 0,
              "toHour": 17,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 19,
              "fromMinute": 0,
              "toHour": 22,
              "toMinute": 0
            },
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 30,
              "toHour": 0,
              "toMinute": 0
            }
          ],
          "tariff_content_sell_tariff_seasons_Summer_tou_periods_SUPER_OFF_PEAK": [
            {
              "fromDayOfWeek": 0,
              "toDayOfWeek": 6,
              "fromHour": 9,
              "fromMinute": 0,
              "toHour": 14,
              "toMinute": 0
            }
          ],
          "tariff_content_sell_tariff_seasons_Winter_fromDay": 0,
          "tariff_content_sell_tariff_seasons_Winter_toDay": 0,
          "tariff_content_sell_tariff_seasons_Winter_fromMonth": 0,
          "tariff_content_sell_tariff_seasons_Winter_toMonth": 0,
          "nameplate_power": 15000,
          "nameplate_energy": 40500,
          "installation_time_zone": "Australia/Brisbane",
          "max_site_meter_power_ac": 1000000000,
          "min_site_meter_power_ac": -1000000000,
          "tariff_content_v2_code": "(edited)",
          "tariff_content_v2_name": "Weekenf (edited)",
          "tariff_content_v2_utility": "Amber",
          "tariff_content_v2_daily_charges": [
            {
              "name": "Charge"
            }
          ],
          "tariff_content_v2_demand_charges_ALL_rates_ALL": 0,
          "tariff_content_v2_energy_charges_ALL_rates_ALL": 0,
          "tariff_content_v2_energy_charges_Summer_rates_OFF_PEAK": 0.15,
          "tariff_content_v2_energy_charges_Summer_rates_ON_PEAK": 0.5,
          "tariff_content_v2_energy_charges_Summer_rates_PARTIAL_PEAK": 0.38,
          "tariff_content_v2_energy_charges_Summer_rates_SUPER_OFF_PEAK": 0.04,
          "tariff_content_v2_seasons_Summer_fromDay": 1,
          "tariff_content_v2_seasons_Summer_toDay": 31,
          "tariff_content_v2_seasons_Summer_fromMonth": 1,
          "tariff_content_v2_seasons_Summer_toMonth": 12,
          "tariff_content_v2_seasons_Summer_tou_periods_OFF_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "toHour": 9
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 14,
              "toHour": 16
            }
          ],
          "tariff_content_v2_seasons_Summer_tou_periods_ON_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 17,
              "toHour": 19
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 22,
              "toHour": 22,
              "toMinute": 30
            }
          ],
          "tariff_content_v2_seasons_Summer_tou_periods_PARTIAL_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 16,
              "toHour": 17
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 19,
              "toHour": 22
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 30
            }
          ],
          "tariff_content_v2_seasons_Summer_tou_periods_SUPER_OFF_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 9,
              "toHour": 14
            }
          ],
          "tariff_content_v2_sell_tariff_name": "Weekenf (edited)",
          "tariff_content_v2_sell_tariff_utility": "Amber",
          "tariff_content_v2_sell_tariff_daily_charges": [
            {
              "name": "Charge"
            }
          ],
          "tariff_content_v2_sell_tariff_demand_charges_ALL_rates_ALL": 0,
          "tariff_content_v2_sell_tariff_energy_charges_ALL_rates_ALL": 0,
          "tariff_content_v2_sell_tariff_energy_charges_Summer_rates_OFF_PEAK": 0.05,
          "tariff_content_v2_sell_tariff_energy_charges_Summer_rates_ON_PEAK": 0.35,
          "tariff_content_v2_sell_tariff_energy_charges_Summer_rates_PARTIAL_PEAK": 0.1,
          "tariff_content_v2_sell_tariff_energy_charges_Summer_rates_SUPER_OFF_PEAK": 0,
          "tariff_content_v2_sell_tariff_seasons_Summer_fromDay": 1,
          "tariff_content_v2_sell_tariff_seasons_Summer_toDay": 31,
          "tariff_content_v2_sell_tariff_seasons_Summer_fromMonth": 1,
          "tariff_content_v2_sell_tariff_seasons_Summer_toMonth": 12,
          "tariff_content_v2_sell_tariff_seasons_Summer_tou_periods_OFF_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "toHour": 9
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 14,
              "toHour": 16
            }
          ],
          "tariff_content_v2_sell_tariff_seasons_Summer_tou_periods_ON_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 17,
              "toHour": 19
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 22,
              "toHour": 22,
              "toMinute": 30
            }
          ],
          "tariff_content_v2_sell_tariff_seasons_Summer_tou_periods_PARTIAL_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 16,
              "toHour": 17
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 19,
              "toHour": 22
            },
            {
              "toDayOfWeek": 6,
              "fromHour": 22,
              "fromMinute": 30
            }
          ],
          "tariff_content_v2_sell_tariff_seasons_Summer_tou_periods_SUPER_OFF_PEAK_periods": [
            {
              "toDayOfWeek": 6,
              "fromHour": 9,
              "toHour": 14
            }
          ],
          "tariff_content_v2_version": 1,
          "vpp_backup_reserve_percent": 0
        }
      }
    ],
    "scopes": [
      "openid",
      "offline_access",
      "user_data",
      "vehicle_device_data",
      "vehicle_cmds",
      "vehicle_charging_cmds",
      "energy_device_data",
      "energy_cmds"
    ]
  }
}
```

**Comment by Bre77** [comment]
Will be fixed in the next release. Thanks as always Mark.

**Comment by Bre77** [comment]
Should be fixed in https://github.com/Teslemetry/hass-teslemetry/releases/tag/v1.9.12

**Comment by purcell-lab** [comment]
Updated to 1.9.12, but still not updating.

Teslemetry downloaded diagnostics matches:

![Screenshot 2024-06-06 17 12 08](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/634777b4-e6e4-4605-9e95-f6b50091749a)

![Screenshot_20240606-171302](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/96d64710-0256-4a29-b3c7-257b10964131)


teslemetry sensor doesn't match & slider doesn't work as it is unknown..
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/bd35a1e5-ea45-4e67-a948-ac96b37570d7)

**Comment by Bre77** [comment]
Mark it turns out the last release didnt actually include the fixes, so .13 might be better.

**Comment by purcell-lab** [comment]
Thanks, functionality is working.  I can change in teslemetry or Tesla app and the endpoint in the powerwall is updated.

Oddly changes in the slide are updated in the Powerwall immediately (by checking API endpoint directly), but are only updated in the Tesla app infrequently. The teslemetry sensor is updated immediately with Tesla app changes.
